path:
  data: '../data'  # data folder

token:
  bos: '<bos>'  # begin of sentence
  eos: '<eos>'  # end of sentence
  pad: '<pad>'  # padding
  unk: '<unk>'  # unknown

sentence_len: 30
vocabulary_size: 20000
batch_size: 64
batches_per_epoch: 100
embeddings_size: 100
